name: Upload project to PyPI

on:
  workflow_call:

jobs:
  check-version:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: 3.12
    - name: Install dependencies
      run: pip install poetry
    - name: Check version
      run: '[[ "$(poetry version -s)" == "${{ github.ref_name }}" ]]'
  dist:
    runs-on: ubuntu-20.04
    needs: check-version
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: python bin/install.py
    - name: Build dist package
      run: python bin/dist.py
    - name: Upload wheel as CI artifact
      uses: actions/upload-artifact@v3
      with:
        name: wheel-${{ github.run_id }}-${{ github.sha }}
        path: ./dist/
  upload:
    runs-on: ubuntu-latest
    needs: dist
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: 3.12
    - name: Install dependencies
      run: python bin/install.py
    - name: Build source distribution (sdist) file
      run: |
        poetry self add "poetry-dynamic-versioning[plugin]"
        poetry build --format=sdist
    - name: Pull the wheel artifacts
      uses: actions/download-artifact@v3
      with:
        name: wheel-${{ github.run_id }}-${{ github.sha }}
        path: ./dist/
    - name: Release packages to PyPI
      run: python bin/release.py -p --pypi-repository ${{ vars.PYPI_REPOSITORY }} --pypi-token ${{ secrets.PYPI_TOKEN }}
